# Generated by Django 5.0.1 on 2024-02-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('tashkil_topgan', models.DateField()),
                ('dars_vaqti', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('familiya', models.CharField(max_length=20)),
                ('tel_raqam', models.CharField(max_length=20)),
                ('manzil', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqam', models.PositiveIntegerField()),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=20)),
                ('narx', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('familya', models.CharField(max_length=30)),
                ('tugilgan_sana', models.DateField()),
                ('tel_raqam', models.CharField(max_length=20)),
                ('manzil', models.CharField(max_length=30)),
                ('guruh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oquv_markaz.guruh')),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.FloatField()),
                ('qarz', models.FloatField()),
                ('chegirma', models.FloatField()),
                ('guruh_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oquv_markaz.guruh')),
                ('oquvchi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oquv_markaz.oquvchi')),
            ],
        ),
        migrations.AddField(
            model_name='guruh',
            name='ustoz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oquv_markaz.ustoz'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='xona_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oquv_markaz.xona'),
        ),
        migrations.AddField(
            model_name='ustoz',
            name='yonalish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oquv_markaz.yonalish'),
        ),
        migrations.AddField(
            model_name='guruh',
            name='yonalish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oquv_markaz.yonalish'),
        ),
    ]
